# Generated by Django 4.2.2 on 2023-06-21 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan_text', models.TextField(max_length=200)),
                ('tanggal_post', models.DateTimeField(verbose_name='tanggal diposting')),
            ],
        ),
        migrations.CreateModel(
            name='Pilihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilihan_text', models.CharField(max_length=50)),
                ('votes', models.IntegerField(default=0)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pertanyaan')),
            ],
        ),
    ]
